#ifndef CTC_ATLAS_GENERATED_H
#define CTC_ATLAS_GENERATED_H

/* Generated by atlas 0.1.0. Do not edit by hand. */

/* Telemetry keys. */
#define CTC_TEL_RENDERER_FRAME_MS "renderer.frame.ms"
#define CTC_TEL_WORKER_QUEUE_DEPTH "worker.queue.depth"
#define CTC_TEL_WORKER_HEARTBEAT_AGE "worker.heartbeat.age"

/* Command names. */
#define CTC_CMD_RENDERER_SET_QUALITY "renderer.set_quality"
#define CTC_CMD_WORKER_DUMP_STATE "worker.dump_state"

#endif /* CTC_ATLAS_GENERATED_H */
